# Generated by Django 5.2.3 on 2025-09-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.CharField(max_length=5000)),
                ("name", models.CharField(max_length=120)),
                ("email", models.CharField(max_length=120)),
                ("Address", models.CharField(max_length=500)),
                ("City", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                ("zipcode", models.CharField(max_length=20)),
            ],
        ),
    ]
